spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: admin123
    #driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)
  jpa:
    properties:
      hibernate:
        show_sql: true
server:
  port: 8801
  servlet:
    context-path: /gen



#logging:
#  level:
#    com.msxf.tool: DEBUG
#  file: log.txt


#swagger:
#  enabled: false
#  title: gen-jpa
#  description: genarate code for jpa
#  version: 1.0.0
#  license: Apache License, Version 2.0
#  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
#  termsOfServiceUrl: https://github.com/olderzhou/
#  contact:
#    name: klaus mikaelson
#    url: http://blog.klausmikaelson.top
#    email: love20141002@126.com
#  base-package: com.klaus.gen
#  base-path: /gen/**
#  #, /swagger-resources/**, swagger-ui.html, /v2/api-docs, /webjars/**
#  exclude-path: /error, /ops/**
#  global-operation-parameters:
#  - { name: access_token, description: user access token, modelRef: string, parameterType: header, required: true}
#  - { name: timestamp, description: access timestamp, modelRef: int, parameterType: header, required: false}
